### PR TITLE
😎 Make file tree look cool

### PR DESCRIPTION
**Pull request by Matt-Gleich**
I also resolved some markdown linting issues.

### CODE REVIEW

**Comment by Matt-Gleich** [comment]
Does that mean that this PR is going to be merged?

**Comment by jackyzha0** [comment]
It's approved so you should be able to merge it in yourself

**Comment by Matt-Gleich** [comment]
Can't. I only have read access as an external contributor

**Comment by Matt-Gleich** [comment]
You or someone else in the project that is a direct contributor has to merge

**Comment by jackyzha0** [comment]
Gotcha, I'll merge it in for you

**Pull request merged**
